include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unnecessary_import: ignore
    unused_import: ignore
    dead_code: ignore
    unused_field: ignore

linter:
  rules:
    avoid_unnecessary_containers: false
    prefer_const_constructors: false
    avoid_print: falsed
