# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BuildWeb

on:
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get
        
      
      - run: flutter analyze lib/
      - run: flutter test test/
      - run: flutter build web --release lib/main.dart
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /ArmFightFlutterApp/
          customArgs: "lib/main.dart"
